### ISSUE TITLE
[Help]: Arabic Value is not saved in database

### ISSUE THREAD

**Issue by Hegabovic** [omar-haris/filament-timezone-field#2]
### What happened?

the dropdown list is in arabic 
and hit save 

the database recieve key ar but inside it english keyword 

is it possible to save en (english ) and ar {arabic }

for example on this shape : 
{"en":"Africa/Blantyre","ar":"افريقيا/بالتيا"}

### How to reproduce the bug

the database recieve key ar but inside it english keyword 

is it possible to save en (english ) and ar {arabic }

for example on this shape : 
{"en":"Africa/Blantyre","ar":"افريقيا/بالتيا"}

### Package Version

2.0.0

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by omar-haris** [comment]
Hi Hegabovic,

Last version is [v1.0.3](https://github.com/omar-haris/filament-timezone-field/releases/tag/v1.0.3) we did not release v2.0.0 yet.

to answer your question you can easily push languages files and change how keys should be saved at your database.

`php artisan vendor:publish --tag="filament-timezone-field-translations"`

then you can find languages files inside your project.

good luck @Hegabovic
